spring:
  application:
    name: spring-security
  jpa:
    # Provide database platform that is being used
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    # Show sql when spring data jpa performs query
    show-sql: true
    properties:
      hibernate:
        # Format queries
        format_sql: true
  datasource:
    # URL connection to database (spring-security is database name)
    url: jdbc:mysql://localhost:3306/spring-security
    # H2 sql Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Database username and password (TODO change these credentials to your own)
    username: root
    password: password
  h2:
    console:
      enabled: true
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
